[env]
JUST_ONE = true

[tools]
# Scripting & Meta
just = "1.42.4"

# Documentation
"ubi:terrastruct/d2" = "0.7.1"

# Database
"go:github.com/printeers/trek" = "0.10.0"

# Protobuf
"ubi:bufbuild/buf" = "1.61.0"

# Go
golangci-lint = "2.7.2"
"ubi:sqlc-dev/sqlc" = "1.30.0"
