[env]
JUST_ONE=true
# Local k3d registry for Skaffold image builds
SKAFFOLD_DEFAULT_REPO="k3d-registry.localhost:5111"

[tools]
# Scripting & Meta
just = "1.42.4"

# Documentation
"ubi:terrastruct/d2" = "0.7.1"

# Database
"go:github.com/printeers/trek" = "0.9.3"

# Kubernetes & Deployment
kubectl = "1.31.4"
helm = "3.16.3"
skaffold = "2.14.0"
k3d = "5.7.5"
