{{- if and $.Values.authzWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-authz-worker
  labels:
    {{- include "fundament.labels" . | nindent 4 }}
    app.kubernetes.io/component: authz-worker
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ $.Values.authzWorker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: authz-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: authz-worker
    spec:
      containers:
        - name: authz-worker
          image: {{ $.Values.images.authzWorker }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-db-fun-authz-worker
                  key: uri
            - name: LOG_LEVEL
              value: {{ $.Values.authzWorker.logLevel }}
            - name: POLL_INTERVAL
              value: {{ $.Values.authzWorker.pollInterval | quote }}
            - name: BATCH_SIZE
              value: {{ $.Values.authzWorker.batchSize | quote }}
            - name: MAX_RETRIES
              value: {{ $.Values.authzWorker.maxRetries | quote }}
            - name: OPENFGA_API_URL
              value: http://{{ $.Release.Name }}-openfga:{{ $.Values.openfga.apiPort | default 8080 }}
            - name: OPENFGA_STORE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-openfga-config
                  key: store-id
            - name: OPENFGA_AUTHORIZATION_MODEL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-openfga-config
                  key: authorization-model-id
{{- end }}
