{{- if $.Values.consoleFrontend.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-frontend-config
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "console-frontend" "component" "frontend") | nindent 4 }}
data:
  config.json: |
    {
      "authnApiUrl": "{{ $.Values.externalUrls.authn }}",
      "organizationApiUrl": "{{ $.Values.externalUrls.organization }}"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "console-frontend" "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ $.Values.consoleFrontend.replicas }}
  selector:
    matchLabels:
      {{- include "fundament.selectorLabels" (dict "root" $ "name" "console-frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fundament.labels" (dict "root" $ "name" "console-frontend" "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: console-frontend
          image: {{ $.Values.images.consoleFrontend }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/assets/config
              readOnly: true
            - name: config
              mountPath: /app/public/assets/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: console-frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: console-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "console-frontend" "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "fundament.selectorLabels" (dict "root" $ "name" "console-frontend") | nindent 4 }}

{{- if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "console-frontend" "component" "frontend") | nindent 4 }}
  {{- if $.Values.ingress.tls.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.tls.clusterIssuer }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls.clusterIssuer }}
  tls:
    - hosts:
        - console.{{ $.Values.ingress.domain }}
      secretName: console-frontend-tls
  {{- end }}
  rules:
    - host: console.{{ $.Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console-frontend
                port:
                  name: http
{{- end }}

{{- end }}
