{{- if $.Values.db.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "fundament.db.name" . }}
  labels:
    {{- include "fundament.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ $.Values.db.instances }}
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: fundament
      owner: fundament
  storage:
    size: {{ $.Values.db.storageSize }}
  managed:
    roles:
      - name: fun_authn_api
        login: true
        passwordSecret:
          name: {{ $.Release.Name }}-db-fun-authn-api
      - name: fun_organization_api
        login: true
        passwordSecret:
          name: {{ $.Release.Name }}-db-fun-organization-api
{{- end }}
