{{- if $.Values.docsFrontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "docs-frontend" "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ $.Values.docsFrontend.replicas }}
  selector:
    matchLabels:
      {{- include "fundament.selectorLabels" (dict "root" $ "name" "docs-frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fundament.labels" (dict "root" $ "name" "docs-frontend" "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: docs-frontend
          image: {{ $.Values.images.docsFrontend }}
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: docs-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "docs-frontend" "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "fundament.selectorLabels" (dict "root" $ "name" "docs-frontend") | nindent 4 }}

{{- if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-frontend
  labels:
    {{- include "fundament.labels" (dict "root" $ "name" "docs-frontend" "component" "frontend") | nindent 4 }}
  {{- if $.Values.ingress.tls.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.tls.clusterIssuer }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls.clusterIssuer }}
  tls:
    - hosts:
        - docs.{{ $.Values.ingress.domain }}
      secretName: docs-frontend-tls
  {{- end }}
  rules:
    - host: docs.{{ $.Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs-frontend
                port:
                  name: http
{{- end }}

{{- end }}
