{{- if $.Values.loginFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-login-frontend
  labels:
    {{- include "fundament.labels" . | nindent 4 }}
    app.kubernetes.io/component: login-frontend
spec:
  replicas: {{ $.Values.loginFrontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: login-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: login-frontend
    spec:
      containers:
        - name: login-frontend
          image: {{ $.Values.images.loginFrontend }}
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-login-frontend
  labels:
    {{- include "fundament.labels" . | nindent 4 }}
    app.kubernetes.io/component: login-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/component: login-frontend
---
{{- if $.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-login-frontend
  labels:
    {{- include "fundament.labels" . | nindent 4 }}
    app.kubernetes.io/component: login-frontend
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  rules:
    - host: login.{{ $.Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-login-frontend
                port:
                  name: http
{{- end }}
{{- end }}
