{{- if and $.Values.openfga.enabled $.Values.outboxWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-outbox-worker
  labels:
    {{- include "fundament.labels" . | nindent 4 }}
    app.kubernetes.io/component: outbox-worker
spec:
  replicas: {{ $.Values.outboxWorker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: outbox-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: outbox-worker
    spec:
      containers:
        - name: outbox-worker
          image: {{ $.Values.images.outboxWorker }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-db-fun-authz-worker
                  key: uri
            - name: LOG_LEVEL
              value: {{ $.Values.outboxWorker.logLevel }}
            - name: POLL_INTERVAL
              value: {{ $.Values.outboxWorker.pollInterval | quote }}
            - name: BATCH_SIZE
              value: {{ $.Values.outboxWorker.batchSize | quote }}
            - name: OPENFGA_API_URL
              value: http://{{ $.Release.Name }}-openfga:{{ $.Values.openfga.playground.apiPort | default 8080 }}
            - name: OPENFGA_STORE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-openfga-config
                  key: store-id
            - name: OPENFGA_AUTHORIZATION_MODEL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-openfga-config
                  key: authorization-model-id
{{- end }}
