apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.11.4
  targetNamespace: ingress-nginx
  createNamespace: true
  valuesContent: |
    controller:
      allowSnippetAnnotations: true
      ingressClassResource:
        default: true
      service:
        externalIPs:
          - 172.19.0.2
