apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: fundament
servers: 1
agents: 0
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 54328:54328
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
registries:
  create:
    name: "registry.localhost"
    host: "0.0.0.0"
    hostPort: "5111"
  config: |
    mirrors:
      "localhost:5111":
        endpoint:
          - http://registry.localhost:5000
volumes:
  - volume: ${PWD}/deploy/k3d/resources/cloudnative-pg.yaml:/var/lib/rancher/k3s/server/manifests/cloudnative-pg.yaml
  - volume: ${PWD}/deploy/k3d/resources/cert-manager.yaml:/var/lib/rancher/k3s/server/manifests/cert-manager.yaml
  - volume: ${PWD}/deploy/k3d/resources/ingress-nginx.yaml:/var/lib/rancher/k3s/server/manifests/ingress-nginx.yaml
